### ISSUE TITLE
EventEmitter docs should indicate that the emitter must be instantiated via util.inherits() and EventEmitter.call(this)

### ISSUE THREAD

**Issue by yunong** [nodejs/node-v0.x-archive#7646]
The current EventEmitter docs: http://nodejs.org/api/events.html do not indicate how one should instantiate an instance of the emitter. 

The blessed procedure is: 
```
tj.fontaine@joyent.com
11:53 you should util.inherits and EventEmitter.call(this)
```

**Comment by brendanashworth** [comment]
This was fixed in https://github.com/nodejs/node/pull/2168 - and because I don't think the doc change will be backported, I'll close this issue for now.

**Comment by targos** [comment]
@brendanashworth even if an issue is still relevant or a fix has to be backported to 0.12 or 0.10, it would be done in nodejs/node.

**Comment by brendanashworth** [comment]
@targos hmm.. is there any reason to leave any of these issues open then? :)

**Comment by targos** [comment]
The only reason I see is for you are doing right now: answering to them, closing and redirecting to nodejs/node if applicable.
