### ISSUE TITLE
Debugger is incredibly slow to start up

### ISSUE THREAD

**Issue by fresheneesz** [nodejs/node-v0.x-archive#9125]
I'm working on a relatively large project in a vagrant virtual machine. Without the debugger, my servers take about 5 seconds to start up (start listening). With the debugger, this process bloats up to 2 minutes or so. The speed once its up is slower, but not nearly 20 times slower. 

Its maddening to have to wait 2 minutes between debug cycles. When it takes 30 seconds to find and fix a change, the 2 minute wait is where most of my time goes. Is there any way to speed this up?

**Comment by askhogan** [comment]
Wow.  I thought this was just me.  I spent an hour today going through each require.  I found mongoose was incredibly slow.

**Comment by hankduan** [comment]
I saw something similar this week. Do you think it could be related to this? https://github.com/joyent/node/issues/9319

**Comment by misterdjules** [comment]
@joyent/node-coreteam Adding this to the 0.12.2 with priority P-1 as it affects a lot of users of the remote debugger. See also https://github.com/iojs/io.js/issues/877.

**Comment by unbornchikken** [comment]
I have made limited progress in investigation, please take a look at my comments there:

https://github.com/iojs/io.js/issues/877#issuecomment-86899374
https://github.com/iojs/io.js/issues/877#issuecomment-87576371

**Comment by ThePixelPro** [comment]
0.12.2 released today and the issue still exists.. any word on this?

**Comment by misterdjules** [comment]
@ThePixelPro Yes, we made the decision to release v0.12.2 to make other important bug fixes available now. The issues that are still open in the 0.12.2 milestone will be moved to the 0.12.3 milestone, and this one specifically will be one of the top priorities for that milestone.

**Comment by ThePixelPro** [comment]
Thanks for the update.  I know I'm not the only one who's looking forward to this fix.  Keep up the good work all.

**Comment by misterdjules** [comment]
@ThePixelPro Thank you for the support, it is very much appreciated :+1:

**Comment by misterdjules** [comment]
@fresheneesz @askhogan @ThePixelPro @unbornchikken I haven't been able to reproduce the issue, do you have some detailed instructions with how I could reproduce that reliably? Does it happen with latest node v0.10 too?

Also, as @hankduan suggested, I have a hunch that it might be related to https://github.com/joyent/node/pull/17203. Would you mind building node with that change and let us know if it fixes your issue? That PR is specific to node v0.10, so if the problem is not present in node v0.10, that won't help. In that case let me know and I can provide you with a change that applies to node v0.12.

Thank you!

**Comment by unbornchikken** [comment]
Hello,

Please read through this thread carefully: https://github.com/iojs/io.js/issues/877

There you can find syntomps, logs, profiling data, repro cases, investigation results from the community, anything that required to identify and fix this isssue. I don't think that this is related to timers. This is realted for processing new JS files: https://github.com/iojs/io.js/issues/877#issuecomment-87576371

I didn't tried node 0.10.37+. Has anyone result from this? If not, I'll try it later.

**Comment by tzaitsev** [comment]
I thought the goal was to get this into 0.12.3 re: "and this one specifically will be one of the top priorities for that milestone."

**Comment by ThePixelPro** [comment]
@tzaitsev see the iojs link from @unbornchikken. (nodejs/io.js#877) toward the bottom they talk about a registry change made in webstorm that solves this issue.  I'm not sure if this is a node core issue, but rather if this is simply something webstorm is doing to handle tooling with sourcemaps.  

Personally, adding the change suggested has made starting the debugger almost instantaneous.  I have not looked into it any further than that because it satisfied my particular need.  Your mileage may vary.

**Comment by tzaitsev** [comment]
@ThePixelPro confirmed faster if you edit the registry on WebStorm and disable js.debugger.v8.use.any.breakpoint 

Good call!

**Comment by alexander-tsig** [comment]
Where can I edit or disable on WebStorm of Mac?
js.debugger.v8.use.any.breakpoint

**Comment by wespen** [comment]
I haven7t found that in Mac registry anywhere

**Comment by alexander-tsig** [comment]
So, isn't there any way to speed up loading of node debug on Mac's WebStorm?

**Comment by tzaitsev** [comment]
In Webstorm (On Mac) (You may have to be running the EAP version of 10)
Click Help and select Find Action...
Type Registry
Find js.debugger.v8.use.any.breakpoint and uncheck it (you can type to find it)

**Comment by jaumard** [comment]
+1 for disabling js.debugger.v8.use.any.breakpoint on IntelliJ with @tzaitsev answer to improve node debug mode but what does js.debugger.v8.use.any.breakpoint exactly ?

**Comment by HereThereBeMonsters** [comment]
+1 too, for disabling js.debugger.v8.use.any.breakpoint on IntelliJ, it's almost as fast as no debug now.

**Comment by shaunwarman** [comment]
Love it!

**Comment by misterdjules** [comment]
A [fix for the issue has landed in V8](https://codereview.chromium.org/1206573004), but it's based on previous changes and I suspect backporting it would be quite involved. @indutny @tunniclm @mhdawson @bnoordhuis Thoughts?

**Comment by hilkeheremans** [comment]
FYI, disabling js.debugger.v8.use.any.breakpoint in WebStorm will disable sourcemap support.

**Comment by bnoordhuis** [comment]
@misterdjules Yes, back-porting would be a lot of work and an ever deepening rabbit hole.  You'll need v8/v8-git-mirror@6434ec30 for the shared_function_infos but that commit depends on previous work as well (e.g. WeakFixedArray, which doesn't exist in 3.28.)

**Comment by danilodeveloper** [comment]
OMG, it is very slow...

**Comment by hilkeheremans** [comment]
This should be fixed in nodejs > v4.0.0. Can anyone else confirm?

**Comment by danilodeveloper** [comment]
@hilkeheremans I'm running nodejs v4.1.1 and the issue still exists.

**Comment by danilodeveloper** [comment]
@hilkeheremans I'm running v4.1.1 and Webstorm 10.0.4 (build #WS-141.1550), everything is ok :+1:

**Comment by cjihrig** [comment]
I'm going to close this, as it appears to be fixed in newer versions of Node and the backport seems involved.

**Comment by davidje** [comment]
Is it back? I still get this issue in 4.2.1 -- how can I confirm its the same exact issue? It only happens with Hapi or Mongo. Its double worse when I require both.  When I commenting out Mongo and Hapi, it speeds it up. What are the steps to verify that I have the same issue? thanks

**Comment by o0x2a** [comment]
I'm using latest version of webstorm 11.0.1 and node v5.0, and debugging node.js code is terribly slow. Vote up for a fix :+1:

**Comment by Pat-rice** [comment]
@code-guru I have node v5.1 and Webstorm 11.0.1 - Also incredibly slow.

**Comment by o0x2a** [comment]
@Pat-rice  use `node-inspector` instead, it's awesome. You may need to have Xcode/Visual Studio installed if you are mac or windows since it needs to compile some stuff when you install it. If you are on Ubuntu/Debian `sudo apt-get install build-essentials` may do the trick.

**Comment by HowlingEverett** [comment]
@code-guru No luck, I'm afraid. This is a NodeJS 5.x issue, not a Webstorm issue. I am seeing similar delays (30+ seconds to attach to a debugging session) using the latest `node-inspector` with NodeJS 5.1.

**Comment by atom0s** [comment]
WebStorm v11.0.3 with Node.js v5.4.1, launching any of my projects in debug mode takes upwards to a minute for it to finally start. This issue is still definitely around.

Edit: This workaround does seem to fix the delay, but as others mentioned it has issues with debugging certain things then:
http://stackoverflow.com/a/31055505/1080150

**Comment by amcsi** [comment]
I'm getting this issue too.

```
/usr/bin/node --debug-brk=33810 --nolazy --harmony dist/server.js
Debugger listening on port 33810
Example app listening at http://:::8080
```

It takes 12 seconds to get from the second output row to the third.

**Comment by indutny** [comment]
@amcsi this is quite expected, I guess. Why are you using `nolazy`?

**Comment by amcsi** [comment]
@indutny WebStorm is adding that bit. The same Debug run that adds `--debug-brk` with a random number.
I'm happy to accept tips on how to disable the `lolazy` bit (couldn't figure that out yet), although I heard that I need that to properly debug async.

**Comment by develar** [comment]
@indutny V8 in lazy mode cannot debug column-based (e.g. lambdas) correctly — https://bugs.chromium.org/p/v8/issues/detail?id=2825
And, as you maybe remember, disabling lazy mode doesn't help — https://github.com/nodejs/node/issues/877#issuecomment-75248842

**Comment by XavierGeerinck** [comment]
Still having this issue too

**Comment by itai-codefresh** [comment]
also me

**Comment by wpoch** [comment]
I'm also having this issue with `/Users/wp/.nvm/versions/node/v5.7.0/bin/node --debug-brk=52887 --nolazy --debug`

**Comment by anyong** [comment]
How is this issue still open after a year? Can never debug my apps properly as they take so long to start up... it's faster to just write a bunch of console.log's and restart the normal server. =/

**Comment by ChALkeR** [comment]
@anyong It's not open, it's closed.

See https://github.com/nodejs/node/issues/877 and https://github.com/nodejs/node/issues/3875 (especially this one).

**Comment by markuswinkler** [comment]
Doesn't seem closed to me. I am running 2016.1 with Node 5.9.1 and starting the debugger takes at least 15 seconds.

**Comment by emascarinas** [comment]
try adding:
--no-preload --hidden='node_modules'

**Comment by amcsi** [comment]
@emascarinas 

```
"C:\f\PhpStorm 2016.1\bin\runnerw.exe" C:\p\nodejs\node.exe --debug-brk=50033 --harmony --no-preload --hidden=node_modules hot.js
C:\p\nodejs\node.exe: bad option: --no-preload
C:\p\nodejs\node.exe: bad option: --hidden=node_modules
```

Those don't appear to be valid node parameters

**Comment by develar** [comment]
@amcsi Nodejs 5 is slow for you, not 4, right? Fix (https://youtrack.jetbrains.com/issue/WEB-19117) will be available in the next PS update (2016.2).

**Comment by amcsi** [comment]
nodejs 5 yea

oh itll be fixed in the next IntelliJ version, cool!

**Comment by rorgonas** [comment]
@emascarinas  Thanks for your solution. It worked well.
Here is the complete e.g.
node-inspector --web-port 1337 --no-preload --hidden='node_modules'

**Comment by amcsi** [comment]
What is this node-inspector, and how is it going to connect to WebStorm?

**Comment by shaunwarman** [comment]
Start up seems fine in version `2016.1`, but now I can't see any breakpoint data. I just see `Collecting data...` forever.

**Comment by develar** [comment]
@shaunwarman Node JS 6 supported, but IDEA with this fix is not yet released.

**Comment by shaunwarman** [comment]
Thanks @develar so I just need to drop node version to 5?

**Comment by develar** [comment]
@shaunwarman Yes. EAP release will be in a few days.

**Comment by shaunwarman** [comment]
Edit: After webstorm update everything works great with the debugger in node v6 👍
