### ISSUE TITLE
Building v0.12.0 on FreeBSD

### ISSUE THREAD

**Issue by ahacking** [nodejs/node-v0.x-archive#9175]
Encountered the following error attempting to build v0.12.0 on FreeBSD:

First attempt, compile using default gcc with `CC=gcc48 CXX=g++48 LINK=g++48 ./configure --prefix=~/.local && gmake`:

```
../deps/v8/src/base/platform/platform-freebsd.cc: In static member function 'static std::vector<v8::base::OS::SharedLibraryAddress> v8::base::OS::GetSharedLibraryAddresses()':
../deps/v8/src/base/platform/platform-freebsd.cc:159:12: error: request for member 'push_back' in 'result', which is of non-class type 'int'
     result.push_back(SharedLibraryAddress(start_of_path, start, end));
            ^
deps/v8/tools/gyp/v8_libbase.target.mk:102: recipe for target '/usr/home/andrew/proj/node-v0.12.0/out/Release/obj.target/v8_libbase/deps/v8/src/base/platform/platform-freebsd.o' failed
```

Second attempt, compile using the system clang compiler also has the same problem: `CC=clang CXX=clang++ LINK=clang++ ./configure --prefix=~/.local && gmake`:

```
../deps/v8/src/base/platform/platform-freebsd.cc
../deps/v8/src/base/platform/platform-freebsd.cc:159:11: error: member reference base type 'int' is not a structure or union
    result.push_back(SharedLibraryAddress(start_of_path, start, end));
    ~~~~~~^~~~~~~~~~
1 error generated.
deps/v8/tools/gyp/v8_libbase.target.mk:101: recipe for target '/usr/home/andrew/proj/node-v0.12.0/out/Release/obj.target/v8_libbase/deps/v8/src/base/platform/platform-freebsd.o' failed
```

Building node v0.10.36 compiles and installs without incident.

**Comment by charlanxcc** [comment]
It's failing because there are two local variables named "result". Change one of the names, then it's going to work.

If you have 64 bit freebsd, however, it's going to fail in platform-posix.cc like the following.

../deps/v8/src/base/platform/platform-posix.cc:331: error: invalid static_cast from type 'pthread*' to type 'int'
 
Change that line to the following, even though it's not really correct.

  return static_cast<int>((int) (int64_t) (void *) pthread_self());

**Comment by staropram** [comment]
diff --git a/deps/v8/src/base/platform/platform-freebsd.cc b/deps/v8/src/base/platform/platform-freebsd.cc
index 09d7ca7..baae689 100644
--- a/deps/v8/src/base/platform/platform-freebsd.cc
+++ b/deps/v8/src/base/platform/platform-freebsd.cc
@@ -122,10 +122,10 @@ static unsigned StringToLong(char* buffer) {
 
 
 std::vector<OS::SharedLibraryAddress> OS::GetSharedLibraryAddresses() {
-  std::vector<SharedLibraryAddress> result;
+  std::vector<SharedLibraryAddress> address_result;
   static const int MAP_LENGTH = 1024;
   int fd = open("/proc/self/maps", O_RDONLY);
-  if (fd < 0) return result;
+  if (fd < 0) return address_result;
   while (true) {
     char addr_buffer[11];
     addr_buffer[0] = '0';
@@ -156,10 +156,10 @@ std::vector<OS::SharedLibraryAddress> OS::GetSharedLibraryAddresses() {
     // There may be no filename in this line.  Skip to next.
     if (start_of_path == NULL) continue;
     buffer[bytes_read] = 0;
-    result.push_back(SharedLibraryAddress(start_of_path, start, end));
+    address_result.push_back(SharedLibraryAddress(start_of_path, start, end));
   }
   close(fd);
-  return result;
+  return address_result;
 }
 
 
diff --git a/deps/v8/src/base/platform/platform-posix.cc b/deps/v8/src/base/platform/platform-posix.cc
index a5128d0..b9ee32b 100644
--- a/deps/v8/src/base/platform/platform-posix.cc
+++ b/deps/v8/src/base/platform/platform-posix.cc
@@ -328,7 +328,7 @@ int OS::GetCurrentThreadId() {
 #elif V8_OS_ANDROID
   return static_cast<int>(gettid());
 #else
-  return static_cast<int>(pthread_self());
+  return static_cast<int> ((int64_t) (void *) pthread_self());
 #endif
 }

**Comment by staropram** [comment]
```
diff --git a/deps/v8/src/base/platform/platform-freebsd.cc b/deps/v8/src/base/platform/platform-freebsd.cc
index 09d7ca7..baae689 100644
--- a/deps/v8/src/base/platform/platform-freebsd.cc
+++ b/deps/v8/src/base/platform/platform-freebsd.cc
@@ -122,10 +122,10 @@ static unsigned StringToLong(char* buffer) {
 
 
 std::vector<OS::SharedLibraryAddress> OS::GetSharedLibraryAddresses() {
-  std::vector<SharedLibraryAddress> result;
+  std::vector<SharedLibraryAddress> address_result;
   static const int MAP_LENGTH = 1024;
   int fd = open("/proc/self/maps", O_RDONLY);
-  if (fd < 0) return result;
+  if (fd < 0) return address_result;
   while (true) {
     char addr_buffer[11];
     addr_buffer[0] = '0';
@@ -156,10 +156,10 @@ std::vector<OS::SharedLibraryAddress> OS::GetSharedLibraryAddresses() {
     // There may be no filename in this line.  Skip to next.
     if (start_of_path == NULL) continue;
     buffer[bytes_read] = 0;
-    result.push_back(SharedLibraryAddress(start_of_path, start, end));
+    address_result.push_back(SharedLibraryAddress(start_of_path, start, end));
   }
   close(fd);
-  return result;
+  return address_result;
 }
 
 
diff --git a/deps/v8/src/base/platform/platform-posix.cc b/deps/v8/src/base/platform/platform-posix.cc
index a5128d0..b9ee32b 100644
--- a/deps/v8/src/base/platform/platform-posix.cc
+++ b/deps/v8/src/base/platform/platform-posix.cc
@@ -328,7 +328,7 @@ int OS::GetCurrentThreadId() {
 #elif V8_OS_ANDROID
   return static_cast<int>(gettid());
 #else
-  return static_cast<int>(pthread_self());
+  return static_cast<int> ((int64_t) (void *) pthread_self());
 #endif
 }
```

**Comment by devnexen** [comment]
Another thing, same file, various mmap call attempts to use MAP_NORESERVE flag. It is purely sun os flag if I m not mistaken. That fails too because of it (at least for me).

**Comment by benpptung** [comment]
It's been Node.js 0.12.7, but I still need to use the @staropram patch to build Node.js on FreeBSD. Is there any chance to see this error fixed in 0.12.8 ?

**Comment by inferiorhumanorgans** [comment]
Yep this issue still exists with Node 0.12.7 and FreeBSD 9.x.  Would definitely be good to see this merged for the next 0.12.x release.

**Comment by dmitrig01** [comment]
:+1: just ran into this, applying the fix above solved it

**Comment by kssd** [comment]
Thanks @staropram
